name: Build and export json

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Save notamextractor jar
        uses: actions/upload-artifact@v3
        with:
          name: notamextractor
          path: target/notamextractor-1.0-SNAPSHOT-jar-with-dependencies.jar

  generate:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Download notamextractor jar
        uses: actions/download-artifact@v3
        with:
          name: notamextractor
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Generate
        run: |
          java -jar ./notamextractor-1.0-SNAPSHOT-jar-with-dependencies.jar countrynotams "Austria" > Austria.json
          java -jar ./notamextractor-1.0-SNAPSHOT-jar-with-dependencies.jar countrynotams "Czech Republic" > Czech_Republic.json
          java -jar ./notamextractor-1.0-SNAPSHOT-jar-with-dependencies.jar countrynotams "France" > France.json
          java -jar ./notamextractor-1.0-SNAPSHOT-jar-with-dependencies.jar countrynotams "Germany" > Germany.json
          java -jar ./notamextractor-1.0-SNAPSHOT-jar-with-dependencies.jar countrynotams "Switzerland" > Switzerland.json
      - name: List
        run: ls -la
