name: Build and export json

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      
      - name: Save notamextractor jar
        uses: actions/upload-artifact@v3
        with:
          name: notamextractor
          path: target/notamextractor-1.0-SNAPSHOT-jar-with-dependencies.jar

  generate:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Download notamextractor jar
        uses: actions/download-artifact@v3
        with:
          name: notamextractor
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Generate
        run: |
          mkdir json
          java -jar ./notamextractor-1.0-SNAPSHOT-jar-with-dependencies.jar countrynotams "Austria" > json/Austria.json
          java -jar ./notamextractor-1.0-SNAPSHOT-jar-with-dependencies.jar countrynotams "Czech Republic" > json/Czech_Republic.json
          java -jar ./notamextractor-1.0-SNAPSHOT-jar-with-dependencies.jar countrynotams "France" > json/France.json
          java -jar ./notamextractor-1.0-SNAPSHOT-jar-with-dependencies.jar countrynotams "Germany" > json/Germany.json
          java -jar ./notamextractor-1.0-SNAPSHOT-jar-with-dependencies.jar countrynotams "Switzerland" > json/Switzerland.json
      
      - name: List
        run: |
          ls -la
          ls -la json
      
      - name: Save jsons
        uses: actions/upload-artifact@v3
        with:
          name: json
          path: json/
          
  publish:
    needs: generate
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout publish repo
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.PUBLISH_REPO }}
          token: ${{ secrets.PUBLISH_REPO_TOKEN }}
          path: publish
          
      - name: Download notam jsons
        uses: actions/download-artifact@v3
        with:
          name: json
          
      - name: List
        run: |
          ls -la
      
      - name: Copy json
        run: |
          mkdir publish/notamdata/
          cp -r json/* publish/notamdata/
      
      - name: Publish
        run: |
          cd publish
          date > notamdata/generated.txt
          git config user.name actions
          git config user.email actions@github.com
          git add .
          git commit -m "generated"
          git push
