name: Generate Json Files

on: [workflow_dispatch]

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Download notamextractor jar
        uses: actions/download-artifact@v3
        with:
          name: notamextractor.jar
      - name: List
        run: ls -la
